services:
  - type: web
    name: yourscorekeeper
    env: node
    plan: starter plus
    buildCommand: yarn --frozen-lockfile --prod=false; blitz db migrate; blitz build
    # If you have an out of memory error, change startCommand to "yarn next start"
    startCommand: blitz start --production
    envVars:
      - key: NODE_ENV
        value: production
