services:
  - type: web
    name: yourscorekeeper
    env: node
    plan: starter plus
    buildCommand: yarn --frozen-lockfile --prod=false; blitz db migrate; blitz build && node postBuild.js
    # If you have an out of memory error, change startCommand to "yarn next start"
    startCommand: blitz start --production
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: yourscorekeeper-db
          property: connectionString
databases:
  - name: yourscorekeeper-db
    plan: standard
